### ISSUE TITLE
Format code with rustfmt?

### ISSUE THREAD

**Issue by wezm** [nkizz/mop3#2]
The Rust toolchain comes with [`rustfmt`](https://github.com/rust-lang/rustfmt) to format code to a standard format, run via `cargo fmt`. Would you be interested in running it on this code or a contribution that did it. I think it would tidy it up and make it look more familiar/idiomatic.

**Comment by miakizz** [comment]
Completed in [bee4898](https://github.com/nkizz/mop3/commit/bee4898716c0e719dfbea76d97fee328cfcd7df5)

Thanks!
