### ISSUE TITLE
Avatars -> `X-Face`-header

### ISSUE THREAD

**Issue by aslakr** [nkizz/mop3#3]
Add avatars as [X-Face](https://en.wikipedia.org/wiki/X-Face "Description of X-face on Wikipedia"). 

I don't think there are any `compface(1)` implementation in Rust (yet). Traditionally made by piping trough netpbm etc. and compface as shown in this online X-Face converter <https://www.dairiki.org/xface/> i.e. somthing like:

```sh
echo  "X-Face:$( curl -s $( curl -s https://mastodon.social/api/v1/accounts/1 | jq  -r .avatar ) | \
  djpeg -grayscale | \
  pnmscale -width 48 -height 48 | \
  pnmpad --width 48 --height 48 | \
  pnmhisteq | \
  pgmtopbm -fs | \
  pbmtoxbm | compface )"
```

results in:

```
X-Face: :Iq]CkX#J|O5E1ZdT>HTzV2'xpv#w:gh$UMHa_5AS<Lc`=qX~4m?^xTtZIv5m?@@r3vR$70
 hR/1]kI$+w@xoXm$u"kz1YyLDMz:`F{{$&.]3zXEEUge%VH$pQc87i7NS:A3QhE_c&qO=Nj`QhEo(K
 {ds:/"(ZU\Arw^P}jFea5BGY,;G?9WPZ|%b*L"<4brSH}ruF&[*X6y=tZPP=}&Cn/6;[oK;Ynl#kxk
 *SZa58&y3UDEf'%%N.r''u.R9:aDs1*5I("j2Wp?}$~K(<y:EexbX?0h%uDg3E{zmSmdmAcZ#^pqxN
 KKdAK{%vRcFow6co2d2^
```

Maybe have an avatar directory of pre-generated files with filenames from hashes of account or avatar-urls?

**Comment by miakizz** [comment]
This currently doesn't have any dependencies outside of rust, so I'd probably rather not add that (plus a caching system for the avatars). Unless you'd like to make a PR behind a runtime flag, I won't be adding that. Thanks for the suggestion though, cool piece of history, I had never heard of that.
