### ISSUE TITLE
More informative subject line

### ISSUE THREAD

**Issue by jeffpc** [nkizz/mop3#6]
I just gave mop3 a try and it is certainly cool.  I am however wondering if there is a sane way to generate more informative subject lines.  When looking at the mailbox, it is hard to gauge whether a thread is interesting enough to read without opening it.

**Comment by miakizz** [comment]
Subject line mentions the author for boosts now, try turning on message preview in your mail client to get more information

**Comment by jeffpc** [comment]
Thanks for the boost improvement.

Not every email client has message previews (e.g., mutt - my MUA of choice).  Other clients may support them, but they tend to drastically increase the amount of space used by a single message on the screen in the list of messages.

I was thinking about it some more, and something as simple as "grab the first 100 chars from the body and stuff them into the subject line" would work well enough.  The idea is to give the user an idea what the content is roughly about.
