### ISSUE TITLE
Persist state between mop3 restarts

### ISSUE THREAD

**Issue by jeffpc** [nkizz/mop3#7]
Restarting mop3 results in the pop3 client (e.g., thunderbird) seeing & downloading the "last n timeline messages" again.  Ideally, mop3 would remember which messages were already fetched (& deleted) to avoid the re-downloads and subsequent duplicates.

**Comment by miakizz** [comment]
Currently mop3 does not keep state, so there's no place to store the last message received, and I don't want to drop random files in the system. Mac mail detects messages with IDs that it has already seen and does not redownload them, maybe moving the messages to some kind of archive would have the same affect?

**Comment by jeffpc** [comment]
Different email clients do different things.  Some dedup in name of saving the user from duplicates, some prefer to show the user exactly what's in the mailbox.  Neither is wrong.

Another result of not having state is that a client may not see all messages if too many arrived between restarts (or possibly even between fetches - if I understood the code right).  Ultimately, I don't know what your goal is for the project, but saving *some* state wouldn't be too difficult (and I bet people wouldn't object to it).
